export const MODELS = [
	{ id: 'todo', name: 'General 2.0', desc: 'Modelo con todo el conocimiento del curso.', title: 'Modelo' },
	{ id: 'pdf', name: 'Pdfs 2.0', desc: 'Modelo con los Pdfs del curso.', title: 'Modelo' },
	{ id: 'video', name: 'Video 2.0', desc: 'Modelo con los videos del docente.', title: 'Modelo' },
	{ id: 'codigo', name: 'Código 1.0', desc: 'Modelo con ejemplos de código.', title: 'Modelo' },
];

export const COLORS = [
	{ id: '#e26821', name: 'Naranja', desc: 'Naranja intenso.', title: 'Tema' },
	{ id: '#2563eb', name: 'Azul', desc: 'Azul profundo.', title: 'Tema' },
	{ id: '#eb2c25', name: 'Rojo', desc: 'Rojo Univalle', title: 'Tema' },
	{ id: '#16a34a', name: 'Verde', desc: 'Verde equilibrado.', title: 'Tema' },
	{ id: '#7c3aed', name: 'Morado', desc: 'Morado oscuro.', title: 'Tema' },
	{ id: '#6b7280', name: 'Gris', desc: 'Gris neutro.', title: 'Tema' },
];

export const PAGES = [
	{ id: '/', name: 'Tus Chats', desc: 'Tu Asistente conversacional FLP.', title: 'Vista' },
	{ id: '/pdfs', name: 'Tus Pdfs', desc: 'Biblioteca de Pdfs del curso.', title: 'Vista' },
	{ id: '/videos', name: 'Tus Videos', desc: 'Videos educativos del curso.', title: 'Vista' },
];

export const DATA = {
	'0': {
		tematica: 'Repaso',
		videos: ['https://www.youtube.com/watch?v=-xmyQ9vPPmw', 'https://www.youtube.com/watch?v=r_4ZQqPVoRU'],
		pdfs: ['0. Introduccion e historia de los lenguajes de programacion', '0.1. Repaso gramaticas I'],
	},
	'1': {
		tematica: 'Especificación recursiva de datos',
		videos: [
			'https://www.youtube.com/watch?v=-xmyQ9vPPmw',
			'https://www.youtube.com/watch?v=JPRyWqSGR_k',
			'https://www.youtube.com/watch?v=VpJGNtKpskI',
			'https://www.youtube.com/watch?v=OyhD6yR9vmY',
			'https://www.youtube.com/watch?v=Vglvl_buuZE',
			'https://www.youtube.com/watch?v=zj2QEeqNyLo',
			'https://www.youtube.com/watch?v=KEyfWgouql0',
			'https://www.youtube.com/watch?v=dIhRmt4Khgw',
			'https://www.youtube.com/watch?v=e_DfC91mtas',
		],
		pdfs: ['1. La relacion entre la induccion y recursion Especificacion de datos'],
	},
	'2': {
		tematica: 'Estrategias para representar datos',
		videos: [
			'https://www.youtube.com/watch?v=oXmddkgASKY',
			'https://www.youtube.com/watch?v=oq0ZwXqmJT0',
			'https://www.youtube.com/watch?v=Wiqa0Xnq_k0',
			'https://www.youtube.com/watch?v=z_uAWdqChmk',
			'https://www.youtube.com/watch?v=hsHRvKwYGU8',
			'https://www.youtube.com/watch?v=5ymi1j8FQuI',
			'https://www.youtube.com/watch?v=DsPWtf9LUqQ',
			'https://www.youtube.com/watch?v=UykkUdFKMNg',
		],
		pdfs: ['2. Estrategias para representar datos'],
	},
	'3': {
		tematica: 'Sintaxis y árboles de sintaxis abstracta',
		videos: [
			'https://www.youtube.com/watch?v=wGuA726RKUM',
			'https://www.youtube.com/watch?v=hwvWxpp6TXo',
			'https://www.youtube.com/watch?v=-axhDvoZYQ0',
			'https://www.youtube.com/watch?v=Wec_PIRX7tY',
			'https://www.youtube.com/watch?v=E_IR22Uw7_o',
			'https://www.youtube.com/watch?v=tkfnonZyeZ0',
			'https://www.youtube.com/watch?v=CWw4bitbiNE',
		],
		pdfs: ['3. Datatype y arboles de sintaxis abstracta'],
	},
	'4': {
		tematica: 'Interpretación y compilación',
		videos: [
			'https://www.youtube.com/watch?v=zL0zWJgVB2E',
			'https://www.youtube.com/watch?v=npoh_p9PFlw',
			'https://www.youtube.com/watch?v=vNQauK4mMHA',
			'https://www.youtube.com/watch?v=RmcKbgU1rbM',
			'https://www.youtube.com/watch?v=f45S2x0W9Wk',
			'https://www.youtube.com/watch?v=3p-1ft_KNbs',
			'https://www.youtube.com/watch?v=rY7EvYy-4B0',
		],
		pdfs: ['4. Semantica de los lenguajes de programacion'],
	},
	'6': {
		tematica: 'Procedimientos y procedimientos recursivos',
		videos: [
			'https://www.youtube.com/watch?v=ojG64qQkdZo',
			'https://www.youtube.com/watch?v=i9J-ekNcLOQ',
			'https://www.youtube.com/watch?v=T-h2Q-EtcNc',
			'https://www.youtube.com/watch?v=XhQKzTxORlo',
			'https://www.youtube.com/watch?v=Qs9Mx82uQrE',
		],
		pdfs: ['6. Procedimientos y procedimientos recursivos'],
	},
	'7': {
		tematica: 'Asignación y paso por referencia',
		videos: [
			'https://www.youtube.com/watch?v=glGvOtFAldY',
			'https://www.youtube.com/watch?v=BZ6YfPlSitA',
			'https://www.youtube.com/watch?v=dVERIOle5zA',
			'https://www.youtube.com/watch?v=-qYggrtY6bQ',
			'https://www.youtube.com/watch?v=m2bDVFw5KXc',
			'https://www.youtube.com/watch?v=gGiwIY4jviU',
			'https://www.youtube.com/watch?v=gswgFVuh48Q',
			'https://www.youtube.com/watch?v=JdPQtJ7O5Z4',
			'https://www.youtube.com/watch?v=WtgIKHO4FcM',
			'https://www.youtube.com/watch?v=NdSjy4I5B-8',
			'https://www.youtube.com/watch?v=Rdvff81e2IY',
			'https://www.youtube.com/watch?v=ShlhAy8owxI',
			'https://www.youtube.com/watch?v=jWgdJYlW6KA',
		],
		pdfs: ['7. Asignacion y paso de parametros'],
	},
	'8': {
		tematica: 'Tipos: conceptos y chequeo',
		videos: [
			'https://www.youtube.com/watch?v=m_Th0xGC8oo',
			'https://www.youtube.com/watch?v=GxyNVcOdTQE',
			'https://www.youtube.com/watch?v=KS3IishsjUM',
			'https://www.youtube.com/watch?v=J8kdPqy64gc',
			'https://www.youtube.com/watch?v=KCAnqIIBwMY',
			'https://www.youtube.com/watch?v=tTJVA-uCnWw',
			'https://www.youtube.com/watch?v=ukFGcDhW2xc',
			'https://www.youtube.com/watch?v=rZR5WOfo5T0',
			'https://www.youtube.com/watch?v=a58oyy--My8',
			'https://www.youtube.com/watch?v=yKNOAasafJI',
		],
		pdfs: ['8. Chequeo de tipos'],
	},
	'9': {
		tematica: 'Inferencia de tipos',
		videos: [],
		pdfs: ['9. Inferencia de tipos', '9.1. Ejemplos inferencia de tipos'],
	},
	'10': {
		tematica: 'Objetos',
		videos: [
			'https://www.youtube.com/watch?v=yCXq0NCG00o',
			'https://www.youtube.com/watch?v=PFEp6jFmshw',
			'https://www.youtube.com/watch?v=ZqTptDxsXCs',
			'https://www.youtube.com/watch?v=fbWUE8jvebo',
			'https://www.youtube.com/watch?v=yXIqoR2-FL0',
			'https://www.youtube.com/watch?v=nJ5ANKnZpfU',
			'https://www.youtube.com/watch?v=LpBRO1CbfZA',
			'https://www.youtube.com/watch?v=Dn_pnE-UGm8',
			'https://www.youtube.com/watch?v=9kgBLpcG2x8',
			'https://www.youtube.com/watch?v=rabG7CAMFOk',
			'https://www.youtube.com/watch?v=nL5i_K0OV_4',
		],
		pdfs: ['10. Objetos'],
	},
};
